spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/sync
    username: sa
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
#      ddl-auto: create

